"""
Topology sweep on REAL LWA carbon data (+ calibrated PL trace).

Same five topologies as scripts/scenario_sweep.py but with real
ENTSO-E / CAISO 2020 carbon-intensity data from
github.com/dos-group/lets-wait-awhile, plus a calibrated PL trace
generated by scripts/generate_pl_trace.py.

The workload remains schema-correct synthetic — the Azure 2019 / 2021
trace files are hosted on Azure storage (azurepublicdatasettraces.blob.
core.windows.net) which is not reachable from the build environment.
The trace loaders accept the published Azure schemas; a single CLI
flag swaps in real workload when locally available.

Output:
  - Console table per topology, mirroring §7.3 of the paper.
  - results/real_topology_sweep.csv with all per-scheduler numbers.
"""
from __future__ import annotations

import csv
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from greenfaas import default_carbon_dir
from greenfaas import (
    FifoScheduler,
    GreenFaaSScheduler,
    GreenFaaSV1Scheduler,
    Region,
    Simulator,
    SpatialScheduler,
    WaitAwhileScheduler,
    generate_workload,
    make_default_function_catalog,
    load_carbon_model_from_dir,
)

PROJ = Path(__file__).resolve().parents[1]


def build_regions_subset(region_ids):
    rtt_pairs = {
        ("FR", "DE"): 15, ("FR", "GB"): 12,
        ("FR", "US-CAISO"): 145, ("FR", "PL"): 30,
        ("DE", "GB"): 20, ("DE", "US-CAISO"): 155, ("DE", "PL"): 15,
        ("GB", "US-CAISO"): 140, ("GB", "PL"): 30,
        ("US-CAISO", "PL"): 170,
    }
    rtt_map = {r: {} for r in region_ids}
    for (a, b), v in rtt_pairs.items():
        if a in region_ids and b in region_ids:
            rtt_map[a][b] = float(v)
            rtt_map[b][a] = float(v)
    return {
        r: Region(region_id=r, name=r, capacity=400,
                  network_rtt_ms=rtt_map[r], pue=1.2)
        for r in region_ids
    }


def run_topology(name, region_ids, carbon_dir, duration_s=24 * 3600.0):
    # Each topology loads only its regions' carbon traces.
    from greenfaas.carbon import CarbonModel
    full_cm = load_carbon_model_from_dir(carbon_dir, step_s=300.0, duration_s=duration_s)
    cm = CarbonModel(traces={r: full_cm.traces[r] for r in region_ids if r in full_cm.traces})

    regions = build_regions_subset(region_ids)
    functions = make_default_function_catalog()
    fn_map = {f.function_id: f for f in functions}

    invocations = generate_workload(
        duration_s=duration_s, base_rate_per_s=2.0,
        functions=functions, region_ids=region_ids, seed=42,
    )

    schedulers = [
        FifoScheduler(),
        WaitAwhileScheduler(threshold_g=200.0, max_defer_s=1800.0),
        SpatialScheduler(max_rtt_ms=80.0),
        GreenFaaSV1Scheduler(forecast_accuracy="perfect", deferrable_rtt_ms=80.0),
        GreenFaaSScheduler(forecast_accuracy="perfect", deferrable_rtt_ms=80.0),
    ]

    results = []
    for sched in schedulers:
        sim = Simulator(regions=regions, functions=fn_map, carbon=cm, scheduler=sched)
        results.append((sched.name, sim.run(invocations).summary()))

    fifo_carbon = results[0][1]["carbon_g"]
    print(f"\n=== {name} | regions: {region_ids} | {len(invocations):,} invocations ===")
    print(f"{'scheduler':<14} {'carbon(g)':>11} {'vs FIFO':>9} "
          f"{'SLA viol':>9} {'cold%':>7}")
    print("-" * 56)
    rows = []
    for n, s in results:
        red = (fifo_carbon - s["carbon_g"]) / fifo_carbon * 100.0 if fifo_carbon else 0.0
        print(f"{n:<14} {s['carbon_g']:>11.2f} {red:>+8.2f}% "
              f"{s['sla_violation_rate']:>9.2%} {s['cold_start_rate']:>7.2%}")
        rows.append({
            "topology": name,
            "regions": "|".join(region_ids),
            "scheduler": n,
            "carbon_g": s["carbon_g"],
            "reduction_pct": red,
            "sla_viol": s["sla_violation_rate"],
            "cold_rate": s["cold_start_rate"],
            "p95_ms": s["p95_latency_ms"],
            "invocations": s["invocations"],
        })
    return rows


def main():
    carbon_dir = str(PROJ / default_carbon_dir())
    print("=" * 72)
    print("Real-carbon topology sweep")
    print("=" * 72)
    print(f"Carbon source: {carbon_dir}")
    print("  DE, FR, GB, US-CAISO: real LWA 2020 (ENTSO-E / CAISO)")
    print("  PL: calibrated synthetic (LWA-documented 791 g mean,")
    print("       coal-base-load diurnal shape, ENTSO-E-format timestamps)")
    print("Workload: schema-correct synthetic (Azure 2019/2021 not fetchable here).")

    all_rows = []
    all_rows += run_topology("Full 5-region (FR/DE/GB/CAISO/PL)",
                             ["FR", "DE", "GB", "US-CAISO", "PL"],
                             carbon_dir)
    all_rows += run_topology("EU-only (FR/DE/GB/PL)",
                             ["FR", "DE", "GB", "PL"],
                             carbon_dir)
    all_rows += run_topology("Coal-belt (DE/GB/PL)",
                             ["DE", "GB", "PL"],
                             carbon_dir)
    all_rows += run_topology("Single-region DE",
                             ["DE"], carbon_dir)
    all_rows += run_topology("Single-region CAISO",
                             ["US-CAISO"], carbon_dir)

    out_path = PROJ / "results" / "real_topology_sweep.csv"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(all_rows[0].keys()))
        w.writeheader()
        for row in all_rows:
            w.writerow(row)
    print(f"\nSaved {len(all_rows)} rows to {out_path}")


if __name__ == "__main__":
    main()
