"""
Run GreenFaaS on real-schema traces.

This script consumes:
  * Azure Functions 2021 per-invocation trace          (sample_data/azure_2021)
    -- OR --
    Azure Functions 2019 aggregated dataset            (sample_data/azure_2019)
  * Hourly carbon CSVs in the Let's-Wait-Awhile schema (sample_data/carbon)

By default it uses the sample files generated by scripts/generate_sample_data.py
so the pipeline runs end-to-end without network access. To run on the real
datasets, point the --azure-2021-csv or --azure-2019-dir and --carbon-dir
flags at directories containing the real files (same schemas).

Usage:
    python scripts/run_real_traces.py                 # use sample data, 2021 mode
    python scripts/run_real_traces.py --source 2019   # use sample data, 2019 mode
    python scripts/run_real_traces.py \
        --azure-2021-csv /path/to/AzureFunctionsInvocationTrace.csv \
        --carbon-dir /path/to/lets-wait-awhile/data
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from greenfaas import (
    FifoScheduler,
    GreenFaaSScheduler,
    GreenFaaSV1Scheduler,
    Region,
    Simulator,
    SpatialScheduler,
    WaitAwhileScheduler,
    load_azure_2021_invocations,
    load_azure_2019_function_durations,
    load_azure_2019_invocation_counts,
    load_carbon_model_from_dir,
    sample_invocations_from_2019,
)
from greenfaas.traces.azure_2021 import assign_regions_roundrobin

SAMPLE_DIR = Path(__file__).resolve().parents[1] / "sample_data"


def build_regions(region_ids):
    """Build Region objects with realistic inter-region RTTs."""
    rtt_pairs = {
        ("FR", "SE"): 35, ("FR", "DE"): 15, ("FR", "GB"): 12,
        ("FR", "US-CAISO"): 145, ("FR", "PL"): 30,
        ("SE", "DE"): 25, ("SE", "GB"): 30, ("SE", "US-CAISO"): 150, ("SE", "PL"): 30,
        ("DE", "GB"): 20, ("DE", "US-CAISO"): 155, ("DE", "PL"): 15,
        ("GB", "US-CAISO"): 140, ("GB", "PL"): 30,
        ("US-CAISO", "PL"): 170,
    }
    rtt_map = {r: {} for r in region_ids}
    for (a, b), v in rtt_pairs.items():
        if a in region_ids and b in region_ids:
            rtt_map[a][b] = float(v)
            rtt_map[b][a] = float(v)
    return {
        r: Region(region_id=r, name=r, capacity=400,
                  network_rtt_ms=rtt_map[r], pue=1.2)
        for r in region_ids
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", choices=["2019", "2021"], default="2021",
                        help="Which Azure dataset format to load.")
    parser.add_argument("--azure-2021-csv",
                        default=str(SAMPLE_DIR / "azure_2021" / "AzureFunctionsInvocationTraceSample.csv"),
                        help="Path to Azure 2021 invocation CSV.")
    parser.add_argument("--azure-2019-dir",
                        default=str(SAMPLE_DIR / "azure_2019"),
                        help="Directory containing Azure 2019 CSVs.")
    parser.add_argument("--carbon-dir",
                        default=str(SAMPLE_DIR / "carbon"),
                        help="Directory containing hourly carbon CSVs.")
    parser.add_argument("--max-rows", type=int, default=None,
                        help="Cap on number of invocations to load.")
    args = parser.parse_args()

    # ------------------------------------------------------------------ #
    # 1. Load carbon model.
    # ------------------------------------------------------------------ #
    print(f"Loading carbon traces from {args.carbon_dir}...")
    carbon = load_carbon_model_from_dir(args.carbon_dir, step_s=300.0)
    region_ids = carbon.regions()
    print(f"  Loaded regions: {region_ids}")
    for r in region_ids:
        vals = carbon.traces[r].values
        mean = sum(vals) / len(vals)
        print(f"    {r}: {len(vals)} samples, mean = {mean:.1f} gCO2/kWh")

    # ------------------------------------------------------------------ #
    # 2. Load workload.
    # ------------------------------------------------------------------ #
    if args.source == "2021":
        print(f"\nLoading Azure 2021 trace from {args.azure_2021_csv}...")
        invocations, functions = load_azure_2021_invocations(
            args.azure_2021_csv,
            default_region=region_ids[0],
            max_rows=args.max_rows,
        )
        # Round-robin assignment across regions for multi-region experiments.
        assignment = assign_regions_roundrobin(list(functions.keys()), region_ids)
        for inv in invocations:
            inv.home_region = assignment.get(inv.function_id, region_ids[0])
    else:
        print(f"\nLoading Azure 2019 sample from {args.azure_2019_dir}...")
        inv_path = next(Path(args.azure_2019_dir).glob("invocations_per_function_md*.csv"))
        dur_path = next(Path(args.azure_2019_dir).glob("function_durations_percentiles*.csv"))
        triggers, counts = load_azure_2019_invocation_counts(str(inv_path))
        durations = load_azure_2019_function_durations(str(dur_path))
        assignment = assign_regions_roundrobin(list(triggers.keys()), region_ids)
        invocations, functions = sample_invocations_from_2019(
            triggers, counts, durations,
            region_assignment=assignment,
            default_region=region_ids[0],
            seed=42,
        )

    print(f"  Loaded {len(invocations):,} invocations across {len(functions):,} functions.")
    if not invocations:
        print("  ERROR: no invocations loaded. Check trace path.")
        return

    # Class breakdown.
    from collections import Counter
    class_counts = Counter(functions[i.function_id].latency_class.value for i in invocations)
    print("  SLA class breakdown:")
    for cls, n in class_counts.most_common():
        print(f"    {cls:<12}: {n:>10,} invocations ({n / len(invocations):.1%})")

    duration_s = invocations[-1].arrival_time + 60.0
    print(f"  Simulated horizon: {duration_s/3600:.1f} hours")

    # ------------------------------------------------------------------ #
    # 3. Build regions and run all schedulers.
    # ------------------------------------------------------------------ #
    regions = build_regions(region_ids)
    schedulers = [
        FifoScheduler(),
        WaitAwhileScheduler(threshold_g=200.0, max_defer_s=1800.0),
        SpatialScheduler(max_rtt_ms=80.0),
        GreenFaaSV1Scheduler(forecast_accuracy="perfect", deferrable_rtt_ms=80.0),
        GreenFaaSScheduler(forecast_accuracy="perfect", deferrable_rtt_ms=80.0),
    ]
    results = []
    for sched in schedulers:
        sim = Simulator(regions=regions, functions=functions, carbon=carbon, scheduler=sched)
        results.append((sched.name, sim.run(invocations)))

    # ------------------------------------------------------------------ #
    # 4. Report.
    # ------------------------------------------------------------------ #
    print(f"\n{'scheduler':<14} {'carbon(g)':>10} {'vs FIFO':>9} {'SLA%':>7} {'cold%':>7} {'p95(ms)':>10}")
    print("-" * 62)
    fifo_carbon = None
    for name, res in results:
        s = res.summary()
        if fifo_carbon is None:
            fifo_carbon = s["carbon_g"]
        reduction = (fifo_carbon - s["carbon_g"]) / fifo_carbon * 100.0 if fifo_carbon else 0.0
        print(f"{name:<14} {s['carbon_g']:>10.2f} {reduction:>+8.2f}% "
              f"{s['sla_violation_rate']:>7.2%} {s['cold_start_rate']:>7.2%} "
              f"{s['p95_latency_ms']:>10.1f}")


if __name__ == "__main__":
    main()
